package se.id21afm.umu.cs.bouldr.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Represents a planned route stored in the local database
 *
 * @param id unique identifier of route, autogenerated by Room.
 * @param imageUri the uri of the image associated with route
 * @param name the name of the route
 * @param grade the routes grade
 * @param notes additional notes related to route
 * @param date the date when the route was created
 * @param markedAsCompleted boolean indicating if route is completed or not
 */
@Entity(tableName = "routes")
data class PlannedRoute(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val imageUri: String,
    val name: String = "",
    val grade: String,
    val notes: String,
    val date: String = getCurrentDate(),
    val markedAsCompleted: Boolean = false
)

/**
 * Gets the current date.
 */
fun getCurrentDate(): String {
    val dateFormat = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault())
    return dateFormat.format(Date())
}